### ISSUE TITLE
Nullability support

### ISSUE THREAD

**Issue by rubengees** [MrHadiSatrio/Alfred#11]
I just found this lib and it is just great!

One thing I would wish for though would be nullability annotations in the generated code, especially since that would improve `Kotlin` interoperability.

This generated code:

```java
public final class NewsViewModelProvider {
  public static NewsViewModel get(FragmentActivity activity) {
    return ViewModelProviders.of(activity, new NewsViewModelFactory())
            .get(NewsViewModel.class);
  }

  public static NewsViewModel get(Fragment fragment) {
    return ViewModelProviders.of(fragment, new NewsViewModelFactory())
            .get(NewsViewModel.class);
  }
}
```

could look like this instead:

```java
public final class NewsViewModelProvider {
  @NonNull public static NewsViewModel get(@NonNull FragmentActivity activity) {
    return ViewModelProviders.of(activity, new NewsViewModelFactory())
            .get(NewsViewModel.class);
  }

  @NonNull public static NewsViewModel get(@NonNull Fragment fragment) {
    return ViewModelProviders.of(fragment, new NewsViewModelFactory())
            .get(NewsViewModel.class);
  }
}
```

**Comment by MrHadiSatrio** [comment]
Hi and thanks for your kind words!

You're right, nullability support would definitely be awesome, especially for those who work with `Kotlin`. That said, since this lib is not exclusive to `Kotlin`, I think we should also consider other nullability annotations available (`JSR-305`, `Android Support Annotations`, `Lombok`, etc.).

What do you think?

**Comment by rubengees** [comment]
`Kotlin` and other tooling like `Android Studio` are actually able to pick up many of the available annotations if present in the bytecode. For `Kotlin`, [these](https://kotlinlang.org/docs/reference/java-interop.html#nullability-annotations) are supported.

Since we are already depending on the `android annotations` through the dependency on `support-v4` (see `gradle dependencies`), we should use those.
